kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
subjects:
- kind: User
  name: system:serviceaccount:myproject:default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: "apps/v1beta2"
kind: Deployment
metadata:
  name: play-clustered-chat
  labels:
    app: play-clustered-chat
spec:
  # The initial number of replicas, if adjusting this, make sure you also adjust
  # the REQUIRED_CONTACT_POINT_NR environment variable.
  replicas: 3
  selector:
    matchLabels:
      app: play-clustered-chat

  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: play-clustered-chat
    spec:
      restartPolicy: Always
      containers:
        - name: play-clustered-chat
          image: "play-clustered-chat:0.3"
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              path: "/ready"
              port: management
            periodSeconds: 10
            initialDelaySeconds: 30
          livenessProbe:
            httpGet:
              path: "/alive"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 30
          env:
            # This is referenced from application.conf, and should match the number of replicas
            - name: REQUIRED_CONTACT_POINT_NR
              value: "3"
            - name: JAVA_OPTS
              value: "-Xms128m -Xmx256m"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: management
              containerPort: 8558
          resources:
            limits:
              cpu: 0.25
              memory: 512Mi
            requests:
              cpu: 0.25
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: play-clustered-chat
  name: play-clustered-chat
spec:
  ports:
    - name: http
      port: 80
      targetPort: 9000
    - name: management
      port: 8558
  selector:
    app: play-clustered-chat
  type: LoadBalancer
